#!/bin/bash
echo -n $(echo "$WATER" | tr -cd 'a-z' | tr 'a-z' '0-9' | awk '{sum += 26^length($0)} END {print sum}')$(echo "$STIR" | tr -cd 'a-z' | tr 'a-z' '0-9' | awk '{sum += 26^length($0)} END {print sum}') | tr '0-9a-p' 'a-z'
